file = open('abc.txt', 'w+')

file.write('1\n')
file.write('2\n')
file.write('3\n')
file.seek(0,0)
print(file.readline(),end='')
print(file.readline(),end='')
print(file.readline(),end='')
print('Lendo linhas:  ')
print(file.read())
print('##############')
file.seek(0,0)
print(file.readline(),end='')
print(file.readline(),end='')
print(file.readline(),end='')
print('##############')
file.seek(0,0)
for linha in file.readlines():
    print(linha, end='')
file.close()
